###########
# site.title, site.path, site.url

title: "Dr. Jekyll's Themes"



defaults:
- scope:
    path: ""
    type: authors
  values:
    layout: author



### use /~geraldb  /~mmistakes etc. for author profile pages (e.g. start with tilde (~))

collections:
  authors:
    output: true
    permalink: /~:name


########
# more settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style:    expanded


plugins:
- jekyll-avatar


exclude:
- README.md
- LICENSE.md
- NOTES.md
- Gemfile
- Gemfile.lock


safe: true
lsi: false
